### ISSUE TITLE
[bug] 한명이 나가면 서버가 종료됩니다.

### ISSUE THREAD

**Issue by Darkcruel** [kimDDong/Chat_bool4jo#15]
[내용]
한명이 나가면 서버가 종료됩니다.
[picture]

![image](https://user-images.githubusercontent.com/22339403/59144303-ee156480-8a10-11e9-9b7a-094c9ad9c5d2.png)

**Comment by kimDDong** [comment]
제가 콘솔에 출력되는 내용을 변경하는 와중에 생긴 버그 같습니다....
수정하겠습니다.

**Comment by kimDDong** [comment]
수정완료!
