### ISSUE TITLE
[bug] 스크롤이 딸려 내려가지 않습니다

### ISSUE THREAD

**Issue by minkwns** [kimDDong/Chat_bool4jo#3]
채팅에 스크롤을 생성하였지만, 대화의 양이 많아지면 채팅이 밑으로 밀려야 되는데 그렇게 되지 않습니다.

**Comment by kimDDong** [comment]
수정했습니다!
![image](https://user-images.githubusercontent.com/22341308/58935268-fdde4000-87a7-11e9-97e9-b390755b9d9e.png)
chat.js 19번 라인 추가했습니다.
